client_id = "87279fa581c1631296fb69507c75082e"
name = "PDForge"
application_url = "https://shopify-production-9645.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/create"
  topics = [ "orders/create" ]

[access_scopes]
scopes = "write_products,write_orders,read_orders"
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://shopify-production-9645.up.railway.app/auth/callback",
  "https://shopify-production-9645.up.railway.app/auth/shopify/callback",
]

[app_proxy]
url = "https://shopify-production-9645.up.railway.app/apps"
subpath = "escape-room"
prefix = "apps"

